apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "2Gi"
    limits.cpu: "3"
    limits.memory: "4Gi"

