apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jovies
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: jovies=ghcr.io/mayne0213/jovies
    argocd-image-updater.argoproj.io/jovies.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Mayne0213/jovies.git
    targetRevision: main
    path: deploy/k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: jovies

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

